import cv2
import numpy as np
import matplotlib.pyplot as plt


def create_fig(images):
    '''
    Docstring for create_fig
    createFig performs the operations necessary to create the output of the images
    generated by the rest of the application
    
    :param images: array of images to be used in the output display
    '''
    fig, axs = plt.subplots(4, 5)

    for i in range(4):
        for j in range(5):
            axs[i, j].imshow(cv2.cvtColor(images[i*3 + j], cv2.COLOR_GRAY2BGR))
            axs[i, j].axis('off')

    column_labels = ["1", "2", "3", "4", "5"]
    for ax, col in zip(axs[0], column_labels):
        ax.set_title(col, fontsize=14, pad=10)

    row_labels = ["Closed", "Opened", "Eroded", "Dilated"]

    row_positions = [.8, .6, .4, .2]

    for label, ypos in zip(row_labels, row_positions):
        fig.text(0.03, ypos, label, va='center', ha='center', rotation=90, fontsize=14)

    fig.canvas.manager.set_window_title("CSC515 Module 5 Critical Thinking 2")

    plt.tight_layout(rect=[0.06, 0, 1, 1])
    plt.show()

def main():
    image = cv2.imread('note.jpg', cv2.IMREAD_GRAYSCALE)
    # h, w = image.shape[:2]
    # width = 600
    # ratio = width / float(w)
    # height = int(h * ratio)
    # iters = 2

    # r_image = cv2.resize(image, (width, height), interpolation=cv2.INTER_AREA)

    _, binary_image = cv2.threshold(image, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3,3))
    # closed_image = cv2.morphologyEx(binary_image, cv2.MORPH_CLOSE, kernel, iterations=iters)
    # opened_image = cv2.morphologyEx(binary_image, cv2.MORPH_OPEN, kernel, iterations=iters)
    # eroded_image = cv2.erode(binary_image, kernel, iterations=iters)
    # dilated_image = cv2.dilate(binary_image, kernel, iterations=iters)

    closed_a, opened_a, eroded_a, dilated_a, stacked_a = [], [], [], [], []
    
    for iter in range(5):
        closed_a.append(cv2.morphologyEx(binary_image, cv2.MORPH_CLOSE, kernel, iterations=iter+1))
        opened_a.append(cv2.morphologyEx(binary_image, cv2.MORPH_OPEN, kernel, iterations=iter+1))
        eroded_a.append(cv2.erode(binary_image, kernel, iterations=iter+1))
        dilated_a.append(cv2.dilate(binary_image, kernel, iterations=iter+1))

    images_a = closed_a + opened_a + eroded_a + dilated_a

    create_fig(images_a)

    # stacked = np.hstack(closed_a)
    # stacked_a.append(np.hstack(closed_a))
    # stacked_a.append(np.hstack(opened_a))
    # stacked_a.append(np.hstack(eroded_a))
    # stacked_a.append(np.hstack(dilated_a))

    # cv2.imshow('Closed Images', np.vstack(stacked_a))
    # cv2.imshow('Closed Cursive Image', closed_image)
    # cv2.imshow('Opened Cursive Image', opened_image)
    # cv2.imshow('Eroded Cursive Image', eroded_image)
    # cv2.imshow('Dilated Cursive Image', dilated_image)
    # cv2.waitKey(0)
    # cv2.destroyAllWindows()

if __name__ == "__main__":
    main()
