import cv2
import numpy as np
import matplotlib.pyplot as plt

IMAGE_PATH = 'note.jpg'

def open_image(img, kernel, iters):
    '''
    Docstring for open_image

    Perform Opening morphological operation on image
    
    :param img: Value for image to be processed
    :param kernel: Kernel value to be used in processing image
    :param iters: number of iterations to perform processing
    '''
    return cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel, iterations=iters)

def close_image(img, kernel, iters):
    '''
    Docstring for close_image

    Perform Closing morphological operation on image
    
    :param img: Value for image to be processed
    :param kernel: Kernel value to be used in processing image
    :param iters: number of iterations to perform processing
    '''
    return cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel, iterations=iters)

def erode_image(img, kernel, iters):
    '''
    Docstring for erode_image

    Perform Erode morphological operation on image
    
    :param img: Value for image to be processed
    :param kernel: Kernel value to be used in processing image
    :param iters: number of iterations to perform processing
    '''
    return cv2.erode(img, kernel, iterations=iters)

def dilate_image(img, kernel, iters):
    '''
    Docstring for dilate_image

    Perform Dilate morphological operation on image
    
    :param img: Value for image to be processed
    :param kernel: Kernel value to be used in processing image
    :param iters: number of iterations to perform processing
    '''
    return cv2.dilate(img, kernel, iterations=iters)

def create_fig(images):
    '''
    Docstring for create_fig
    createFig performs the operations necessary to create the output of the images
    generated by the rest of the application
    
    :param images: array of images to be used in the output display
    '''
    fig, axs = plt.subplots(4, 5)

    for i in range(4):
        for j in range(5):
            axs[i, j].imshow(cv2.cvtColor(images[i*3 + j], cv2.COLOR_GRAY2BGR))
            axs[i, j].axis('off')

    column_labels = ["1", "2", "3", "4", "5"]
    for ax, col in zip(axs[0], column_labels):
        ax.set_title(col, fontsize=14, pad=10)

    row_labels = ["Closed", "Opened", "Eroded", "Dilated"]

    row_positions = [.8, .6, .4, .2]

    for label, ypos in zip(row_labels, row_positions):
        fig.text(0.03, ypos, label, va='center', ha='center', rotation=90, fontsize=14)

    fig.canvas.manager.set_window_title("CSC515 Module 5 Critical Thinking 2")

    plt.tight_layout()
    plt.show()

def main():
    '''
    Docstring for main
    
    Process image with mutiple morphological operations performing multiple iterations of the operation and 
    presenting the results in a subplot grid to be able to compare the output to see what values
    provided the best results
    '''
    # Load image into cv2
    img = cv2.imread(IMAGE_PATH, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise FileNotFoundError(f'Image not found at {IMAGE_PATH}')
    # Convert image into binary image
    _, binary_image = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    # create elliptical kernel with 3 x 3 matrix
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3,3))
    # initilize arrays to store images 
    closed_a, opened_a, eroded_a, dilated_a = [], [], [], []
    # process image multiple times to identify most valuable results
    for iter in range(1,6):
        closed_a.append(close_image(binary_image, kernel, iter))
        opened_a.append(open_image(binary_image, kernel, iter))
        eroded_a.append(erode_image(binary_image, kernel, iter))
        dilated_a.append(dilate_image(binary_image, kernel, iter))
    # combine image arrays for most subplot generation
    images_a = closed_a + opened_a + eroded_a + dilated_a
    # generate subplot
    create_fig(images_a)


if __name__ == "__main__":
    main()
